In [ ]:

import pandas as pd
import numpy as np



In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files

uploaded = files.upload()



Saving IBM_HR.csv to IBM_HR.csv


In [ ]:

df = pd.read_csv('IBM_HR.csv')

/tmp/ipython-input-441476710.py:1: DtypeWarning: Columns (5,8,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('IBM_HR.csv')


In [ ]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Employee Source
0,41.0,Voluntary Resignation,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,1,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,Referral
1,41.0,Voluntary Resignation,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,1,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,Referral
2,41.0,Voluntary Resignation,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,7,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,Referral
3,41.0,Voluntary Resignation,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,8,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,Referral
4,41.0,Voluntary Resignation,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,9,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,Referral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23431,60.0,Current employee,Travel_Rarely,370.0,Research & Development,1.0,4.0,Medical,1,19344,...,80.0,1.0,20.0,2.0,3.0,20.0,7.0,2.0,13.0,Company Website
23432,60.0,Current employee,Travel_Rarely,370.0,Research & Development,1.0,4.0,Life Sciences,1,19345,...,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0,Company Website
23433,NaN,Voluntary Resignation,Travel_Frequently,1009.0,Research & Development,1.0,3.0,Life Sciences,1,16794,...,80.0,2.0,4.0,2.0,2.0,2.0,1.0,2.0,2.0,Adzuna
23434,NaN,Current employee,Travel_Rarely,1354.0,Research & Development,5.0,3.0,Medical,1,1956,...,80.0,0.0,14.0,6.0,3.0,11.0,10.0,5.0,8.0,Indeed


In [ ]:
df.dtypes

,0
Age,float64
Attrition,object
BusinessTravel,object
DailyRate,float64
Department,object
DistanceFromHome,object
Education,float64
EducationField,object
EmployeeCount,object
EmployeeNumber,object


In [ ]:
df.ndim

2

In [ ]:
df.isnull().sum()


,0
Age,3
Attrition,13
BusinessTravel,8
DailyRate,12
Department,11
DistanceFromHome,9
Education,12
EducationField,9
EmployeeCount,5
EmployeeNumber,1


In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encoders = {}

for col in df.select_dtypes(include='object').columns:

    df[col] = df[col].astype(str).fillna('Unknown')
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [ ]:

x=df.drop('Attrition',axis=1)
y=df['Attrition']

In [ ]:
x

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,Application ID,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Employee Source
0,41.0,2,1102.0,3,0,2.0,2,0,0,0,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,9
1,41.0,2,1102.0,3,0,2.0,2,0,0,2,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,9
2,41.0,2,1102.0,3,0,2.0,2,0,20055,6,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,9
3,41.0,2,1102.0,3,0,2.0,2,0,21158,7,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,9
4,41.0,2,1102.0,3,0,2.0,2,0,22266,8,...,80.0,0.0,8.0,0.0,1.0,6.0,4.0,0.0,5.0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23431,60.0,2,370.0,2,1,4.0,4,0,10319,19268,...,80.0,1.0,20.0,2.0,3.0,20.0,7.0,2.0,13.0,3
23432,60.0,2,370.0,2,1,4.0,2,0,10320,19269,...,80.0,1.0,19.0,2.0,4.0,1.0,0.0,0.0,0.0,3
23433,NaN,1,1009.0,2,1,3.0,2,0,7511,16742,...,80.0,2.0,4.0,2.0,2.0,2.0,1.0,2.0,2.0,2
23434,NaN,2,1354.0,2,49,3.0,4,0,10557,1946,...,80.0,0.0,14.0,6.0,3.0,11.0,10.0,5.0,8.0,5


In [ ]:
y

,Attrition
0,1
1,1
2,1
3,1
4,1
...,...
23431,0
23432,0
23433,1
23434,0


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])



/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['Accuracy']
)


In [ ]:
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - Accuracy: 0.8391 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 2/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - Accuracy: 0.8401 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 3/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - Accuracy: 0.8439 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 4/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - Accuracy: 0.8421 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 5/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - Accuracy: 0.8398 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 6/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - Accuracy: 0.8398 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 7/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - Accuracy: 0.8423 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 8/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - Accuracy: 0.8458 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 9/20
469/469 ━━━━━

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:

loss, accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8231 - loss: nan
Test Accuracy: 0.8310580253601074


In [ ]:
y_pred = (model.predict(x_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy: 0.8310580204778157

Classification Report:
               precision    recall  f1-score   support

           0       0.83      1.00      0.91      3896
           1       0.00      0.00      0.00       787
           2       0.00      0.00      0.00         5

    accuracy                           0.83      4688
   macro avg       0.28      0.33      0.30      4688
weighted avg       0.69      0.83      0.75      4688


Confusion Matrix:
 [[3896    0    0]
 [ 787    0    0]
 [   5    0    0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
model2 = Sequential([
    Dense(128, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['Accuracy']
)

In [ ]:
history2 = model2.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - Accuracy: 0.8335 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 2/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - Accuracy: 0.8442 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 3/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - Accuracy: 0.8380 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 4/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - Accuracy: 0.8412 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 5/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - Accuracy: 0.8426 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 6/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - Accuracy: 0.8390 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 7/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - Accuracy: 0.8448 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 8/20
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - Accuracy: 0.8401 - loss: nan - val_Accuracy: 0.8541 - val_loss: nan
Epoch 9/20
469/469 ━━━━━

In [ ]:
y_pred2= (model2.predict(x_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred2))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Accuracy: 0.8310580204778157

Classification Report:
               precision    recall  f1-score   support

           0       0.83      1.00      0.91      3896
           1       0.00      0.00      0.00       787
           2       0.00      0.00      0.00         5

    accuracy                           0.83      4688
   macro avg       0.28      0.33      0.30      4688
weighted avg       0.69      0.83      0.75      4688


Confusion Matrix:
 [[3896    0    0]
 [ 787    0    0]
 [   5    0    0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:

loss_model1, accuracy_model1 = model.evaluate(x_test, y_test, verbose=0)
loss_model2, accuracy_model2 = model2.evaluate(x_test, y_test, verbose=0)

print(f"Model 1 Test Accuracy: {accuracy_model1:.4f}")
print(f"Model 2 Test Accuracy: {accuracy_model2:.4f}")

Model 1 Test Accuracy: 0.8311
Model 2 Test Accuracy: 0.8311
